BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE cv';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE TABLE moderator(
  email VARCHAR(255) PRIMARY KEY NOT NULL,
  neve VARCHAR NOT NULL,
  jelszo VARCHAR not NULL
)